# Generated by Django 4.2 on 2025-12-05 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=8)),
                ("vagas", models.IntegerField()),
                ("vagas_disponiveis", models.IntegerField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Vaquejada",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("data_evento", models.DateTimeField()),
                ("local", models.CharField(max_length=255)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(default="CE", max_length=2)),
                ("telefone_contato", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("inativo", "Inativo"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="ativo",
                        max_length=10,
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="vaquejadas/"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Vaquejadas",
                "ordering": ["-data_evento"],
            },
        ),
        migrations.CreateModel(
            name="Senha",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero_senha", models.CharField(max_length=10, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("paga", "Paga"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
                ),
                (
                    "comprovante_pix",
                    models.FileField(blank=True, null=True, upload_to="comprovantes/"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("pago_em", models.DateTimeField(blank=True, null=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="senhas",
                        to="core.categoria",
                    ),
                ),
                (
                    "vaqueiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="senhas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Senhas",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("pix", "PIX"),
                            ("transferencia", "Transferência"),
                            ("dinheiro", "Dinheiro"),
                        ],
                        default="pix",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("confirmado", "Confirmado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                (
                    "comprovante",
                    models.FileField(blank=True, null=True, upload_to="comprovantes/"),
                ),
                ("chave_pix", models.CharField(blank=True, max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("confirmado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "senha",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamento",
                        to="core.senha",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pagamentos",
            },
        ),
        migrations.AddField(
            model_name="categoria",
            name="vaquejada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorias",
                to="core.vaquejada",
            ),
        ),
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome_completo", models.CharField(max_length=255)),
                ("cpf", models.CharField(max_length=14)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=20)),
                ("endereco", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=10)),
                ("complemento", models.CharField(blank=True, max_length=100)),
                ("bairro", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
                ("cep", models.CharField(max_length=10)),
                ("data_nascimento", models.DateField()),
                (
                    "documento",
                    models.FileField(blank=True, null=True, upload_to="documentos/"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "senha",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscricao",
                        to="core.senha",
                    ),
                ),
                (
                    "vaqueiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscricoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inscrições",
                "unique_together": {("vaqueiro", "senha")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="categoria",
            unique_together={("vaquejada", "nome")},
        ),
    ]
