# Generated by Django 4.2 on 2025-12-05 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingresso",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "representacao",
                    models.CharField(max_length=255, verbose_name="Representação"),
                ),
                ("puxador", models.CharField(max_length=255, verbose_name="Puxador")),
                ("esteiro", models.CharField(max_length=255, verbose_name="Esteiro")),
                (
                    "cavalo_puxador",
                    models.CharField(max_length=255, verbose_name="Cavalo do Puxador"),
                ),
                (
                    "cavalo_esteiro",
                    models.CharField(max_length=255, verbose_name="Cavalo do Esteiro"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Aberto"),
                            ("closed", "Fechado"),
                            ("paid", "Pago"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qrcodes/",
                        verbose_name="QR Code PIX",
                    ),
                ),
                (
                    "comprovante_pix",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="comprovantes_pix/",
                        verbose_name="Comprovante PIX",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("pago_em", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Ingresso",
                "verbose_name_plural": "Ingressos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.RemoveField(
            model_name="pagamento",
            name="senha",
        ),
        migrations.RemoveField(
            model_name="senha",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="senha",
            name="vaqueiro",
        ),
        migrations.AlterModelOptions(
            name="categoria",
            options={
                "ordering": ["vaquejada", "nome"],
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.AlterModelOptions(
            name="vaquejada",
            options={
                "ordering": ["-dia", "-hora"],
                "verbose_name": "Vaquejada",
                "verbose_name_plural": "Vaquejadas",
            },
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="vagas",
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="vagas_disponiveis",
        ),
        migrations.RemoveField(
            model_name="vaquejada",
            name="cidade",
        ),
        migrations.RemoveField(
            model_name="vaquejada",
            name="data_evento",
        ),
        migrations.RemoveField(
            model_name="vaquejada",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="vaquejada",
            name="telefone_contato",
        ),
        migrations.AddField(
            model_name="categoria",
            name="n_ingressos",
            field=models.IntegerField(
                default=50, verbose_name="Quantidade de Ingressos"
            ),
        ),
        migrations.AddField(
            model_name="vaquejada",
            name="dia",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data do Evento"
            ),
        ),
        migrations.AddField(
            model_name="vaquejada",
            name="hora",
            field=models.TimeField(default="14:00", verbose_name="Hora do Evento"),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome da Categoria"),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="valor",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Valor"
            ),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="vaquejada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorias",
                to="core.vaquejada",
                verbose_name="Vaquejada",
            ),
        ),
        migrations.AlterField(
            model_name="vaquejada",
            name="descricao",
            field=models.TextField(blank=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="vaquejada",
            name="local",
            field=models.CharField(max_length=255, verbose_name="Local/Rancho"),
        ),
        migrations.AlterField(
            model_name="vaquejada",
            name="nome",
            field=models.CharField(max_length=255, verbose_name="Nome da Vaquejada"),
        ),
        migrations.AlterField(
            model_name="vaquejada",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Aberta"),
                    ("closed", "Fechada"),
                    ("cancelled", "Cancelada"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Inscricao",
        ),
        migrations.DeleteModel(
            name="Pagamento",
        ),
        migrations.DeleteModel(
            name="Senha",
        ),
        migrations.AddField(
            model_name="ingresso",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingressos",
                to="core.categoria",
                verbose_name="Categoria",
            ),
        ),
        migrations.AddField(
            model_name="ingresso",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingressos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
