# Generated by Django 4.2 on 2025-12-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_ingresso_remove_pagamento_senha_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingresso",
            name="numero_senha",
            field=models.IntegerField(default=1, verbose_name="Número da Senha"),
        ),
        migrations.AlterUniqueTogether(
            name="ingresso",
            unique_together={("categoria", "numero_senha")},
        ),
    ]
